services:
  telegram:
    image: mykytaproks/vpn_bot_telegram:${TAG}
    command: sh -c "poetry run python telegram/main.py"
    environment:
      - API_KEY_LINODE=${API_KEY_LINODE}
      - ALLOWED_CHAT_IDS=${ALLOWED_CHAT_IDS}
      - STACKSCRIPT_ID=${STACKSCRIPT_ID}
      - SHADOWSOCKS_PASSWORD=${SHADOWSOCKS_PASSWORD}
      - BOT_API_KEY=${BOT_API_KEY}
